import type React from "react"
import { LanguageProvider } from "@/lib/language-context"
import ClientLayout from "./clientLayout"
import type { Metadata } from "next"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.app'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <LanguageProvider>
      <ClientLayout>{children}</ClientLayout>
    </LanguageProvider>
  )
}
